Added a Dice game folder
PeanutCoffee/MiniProjects pull request #110
Opened 2022-10-16 21:41 UTC by hellovaibhav

I have files of a web dice game which is created using html , css and javascript.

2022-10-16 21:47 UTC, hellovaibhav commented
please do mark it with hacktober fest tags 🙂🙂

2022-10-17 04:02 UTC, Wilson0406 requested changes
@hellovaibhav Please add a screenshot of the website.

2022-10-17 07:28 UTC, hellovaibhav commented
> @hellovaibhav Please add a screenshot of the website.

Here are some screenshots

![image](https://user-images.githubusercontent.com/82583704/196114766-121699e2-9a35-4625-ad07-5adcbd8e31cd.png)

![image](https://user-images.githubusercontent.com/82583704/196114779-5133556a-f48c-4a64-8ff0-5c18bca5e660.png)

![image](https://user-images.githubusercontent.com/82583704/196114799-a8b7b921-0bdd-403c-a56c-fd84864470c9.png)

The game runs whenever you refresh the page

2022-10-17 08:47 UTC, Wilson0406 approved these changes

2022-10-17 08:48 UTC, merged